In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [21]:
data = pd.read_csv('real_estate_price_size_year.csv')

In [22]:
data.head()

        price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

In [23]:
data.describe()

               price         size         year
count     100.000000   100.000000   100.000000
mean   292289.470160   853.024200  2012.600000
std     77051.727525   297.941951     4.729021
min    154282.128000   479.750000  2006.000000
25%    234280.148000   643.330000  2009.000000
50%    280590.716000   696.405000  2015.000000
75%    335723.696000  1029.322500  2018.000000
max    500681.128000  1842.510000  2018.000000

In [24]:
x = data[['size','year']]
y = data['price']

In [25]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [26]:
reg.coef_

array([ 227.70085401, 2916.78532684])

In [27]:
reg.intercept_

np.float64(-5772267.017463279)

Calculating the R-squared

In [28]:
reg.score(x,y)

0.7764803683276795

In [29]:
x.shape

(100, 2)

In [30]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]
adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.7718717161282502

In [31]:
from sklearn.feature_selection import f_regression

In [32]:
f_regression(x,y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [33]:
p_values = f_regression(x,y)[1]
p_values

array([8.12763222e-31, 3.57340758e-01])

In [34]:
p_values.round(3)

array([0.   , 0.357])

Creating a summary table

In [ ]:
reg_summary = pd.DataFrame(data = x.columns.values ,columns=['Features'])
reg_summary

In [19]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)

In [20]:
reg_summary

  Features  Coefficients  p-values
0     size    227.700854     0.000
1     year   2916.785327     0.357